### ISSUE TITLE
plugin_customization.ini

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.docbook#3]
Inside the [Product (Site) Defaults: plugin_customization.ini](http://cs-studio.sourceforge.net/docbook/ch06.html#idp455920) section the following is written:

> The file has to be in the plugin that defines the product. For example, assume you have a product X that is defined in `org.csstudio.x.y/X.product`. Eclipse will look for a file `org.csstudio.x.y/plugin_customization.ini`, i.e. a customization file in the root directory of the plugin that defines the product, for settings to override values from individual plugins.

In the _org.csstudio.ess.product_ I've found this file inside `/org.csstudio.ess.product/features/org.csstudio.ess.product.configuration.feature/rootfiles/configuration/`, that is inside the `rootfiles/configuration` folder of the product's configuration feature.

Moreover:

> In the compiled version of the product, plugins are usually JAR files in a `plugins` sub-directory of the installed product. The customization file will then be found inside `plugins/org.csstudio.x.y_*.jar` where the \* represents some version number and date.

Again, in CS-Studio (the version Kunal has given to ESS inside the training VM) this file can be found in the `configuration` folder.

Have I misunderstood something?

**Comment by kasemir** [comment]
By default, including eclipse itself, that plugin_customization file was in the product's root directory.
But you can configure Eclipse to look elsewhere via the preferenceCustomization setting in the product's plugin.xml file.

https://github.com/ControlSystemStudio/org.csstudio.product/blob/master/plugins/org.csstudio.product/plugin.xml sets that to value="platform:/config/plugin_customization.ini", so now Eclipse looks for it in the configuration directory.

For the products I build at SNS (alarm-config, alarm-notifier, alarm-server, archive-config, archive-engine, basic-epics, scan-server, sns-css) I didn't bother to change the default.

This is again an example where it'll be very hard to duplicate the complete Eclipse documentation.

**Comment by claudio-rosati** [comment]
Now I understand.
Thank you very much for your help.

**Comment by claudio-rosati** [comment]
I'll fork the project, add a note about possible differences caused by a different settings in Eclipse a I'll issue a pull request.
Thank you
P.S.
I agree with you about maven/ant

**Comment by kasemir** [comment]
I've updated the doc to mention the preferenceCustomization setting.
