### ISSUE TITLE
Wrong description of platform:/config/plugin_customization.ini

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.docbook#5]
On chapter 6, in the **Product (Site) Defaults: plugin_customization.ini** section, 4th paragraph, the following it is written:

> For example, if `preferenceCustomization` is set to `platform:/config/plugin_customization.ini`, the customization file will need to be in `org.csstudio.x.y/configuration/plugin_customization.ini`.

According to [Eclipse Documentation](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fplugin_manifest.html) about the `platform:/config` scheme:

> The "config" segment causes the platform URI to refer to the configuration area of the running Eclipse (usually the _eclipse/configuration_ directory). This can be useful to read the _config.ini_ file, for example.

So, what said in the aforementioned 4th paragraph and the following one seems more related to the `platform:/plugin/org.csstudio.x.y/configuration/plugin_customization.ini` instead of `platform:/config/plugin_customization.ini`.

Thus the 4th paragraph should be updated with `platform:/plugin/org.csstudio.x.y/configuration/plugin_customization.ini`  and a new paragraph should be added for the `platform:/config/plugin_customization.ini`one, or be reworked.

Claudio

**Comment by kasemir** [comment]
The product that FRIB, BNL and I think also ESS use is based on 
https://github.com/ControlSystemStudio/org.csstudio.product/blob/master/plugins/org.csstudio.product/plugin.xml
which sets 

```
<property
         name="preferenceCustomization"
         value="platform:/config/plugin_customization.ini">
</property>
```

Example: When I download `cs-studio-nsls2-4.3.1-linux.gtk.x86_64.tar.gz`, it contains `cs-studio/configuration/plugin_customization.ini`, and I assume that's the customization file that's actually used.

From that I think the docbook is correct: If you set `preferenceCustomization` to `platform:/config/plugin_customization.ini` (no `plugin/some.plugin/` in there), the resulting configuration file will be in the `configuration` directory of the product directory tree. It's not under any specific plugin/xyz directory.

**Comment by claudio-rosati** [comment]
Sorry but for me `org.csstudio.x.y/configuration/plugin_customization.ini` was misleading, letting me think it was inside the plugin itself, being that in the rest of the chapter `org.csstudio.x.y` was used to indicate a plugin, not the custom CS-Studio application.

**Comment by kasemir** [comment]
Ah, you're right. 
How about this text:

```
For example, if preferenceCustomization is set to platform:/config/plugin_customization.ini, the customization file will need to be in your_product/configuration/plugin_customization.ini.
```

**Comment by kasemir** [comment]
Tweaked it: 0135e7a9fe89c26919b702792498ca43454a25f8

**Comment by claudio-rosati** [comment]
Yes, this is better. Thank you
